language: node_js

node_js:
  - '11'

script:
  - echo "Check coverage"
  - npm run test:coverage
  - echo "Check formating"
  - npm run format:check
  - echo "Build the component and Storybook"
  - npm run build:all

after_success:
  - echo "All good!"
