language: node_js

node_js:
  - '12'
  - '11'
  - '10'
  - '9'

install:
  - npm install
  - npm install -g codecov

script:
  - echo "Check coverage"
  - npm run test:coverage
  - echo "Check formating"
  - npm run format:check
  - echo "Build the component and Storybook"
  - npm run build:all
  - echo "Upload coverage"
  - codecov --token="$CODECOV_TOKEN"

after_success:
  - echo "All good!"

before_deploy:
  - echo "Ready to Deploy"

deploy:
  provider: npm
  skip_cleanup: true
  email: '$EMAIL'
  api_key:
    secure: '$NPM_TOKEN'
  on:
    tags: true
    repo: Danilo-Zekovic/react-tableql
    branch: master

after_deploy:
  - echo "Deploy over."
