version: '3'
services:
  tableql-dev:
    build: .
    ports:
      - '3000:3000' # CRA
      - '4000:4000' # Next.js
      - '5000:5000' # Gatsby.js (not yet implemented)
      - '6000:6000' # Remix.js (not yet implemented)
      - '7000:7000' # Vite.js (not yet implemented)
      - '8000:8000' # not sure yet
      - '8080:8080' # API (in progress)
    volumes:
      # - .:/app
      # - /app
      - './:/app' # HOT Reload enabled
    links:
      - db
    environment:
      DATABASE_URL: mongodb://db:27017
  db:
    image: mongo:6
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - ./examples/api/db_data:/data/db
